from utils import call_llm

prompt="""Đây là tin nhắn hiện tại của khách hàng cùng với lịch sử trò chuyện từ cũ tới mới nhất. 
            Tin nhắn trước đó: { 'customer': 'cho mình xem vài cái áo thun', 'bot': 'Dạ, mình có vài mẫu áo thun nam đang được ưa chuộng lắm ạ. Anh xem qua mấy mẫu này nha:\n\n1.  **Áo Thun Nam Cotton 220GSM Basics** (Mã: TSZ959)\n    Chất liệu 100% Cotton Úc dày dặn, mềm mịn, thoáng khí, chống xù lông. Form Regular Fit thoải mái, dễ mặc hàng ngày.\n    <img src="https://n7media.coolmate.me/uploads/February2025/ao-thun-nam-cotton-220gsm-mau-nau-cappuccino_(7).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/February2025/ao-thun-nam-cotton-220gsm-mau-xam-castlerock_(8).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/February2025/ao-thun-nam-cotton-220gsm-mau-hong-peach-whip_(7).jpg" width=300>\n\n2.  **Áo Thun Nam Chạy Bộ Graphic Heartbeat** (Mã: TSZ877)\n    Siêu nhẹ, nhanh khô, thấm hút tốt, co giãn 4 chiều. Chất liệu polyester pha spandex giúp vận động thoải mái. Có logo phản quang an toàn.\n    <img src="https://n7media.coolmate.me/uploads/July2025/ao-thun-nam-chay-bo-hoat-tiet-graphic-heartbeat-hong-5.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/May2024/23CMAW.AT003.fixmau19_17.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/July2025/ao-thun-nam-chay-bo-hoat-tiet-graphic-heartbeat-den-3.jpg" width=300>\n\n3.  **Áo Thun Nam Thể Thao Coolmate Basics** (Mã: TSZ916)\n    Chất liệu tái chế (Recycle), siêu nhẹ, thấm hút và khô nhanh. Form Regular Fit năng động, phù hợp cho cả tập luyện và mặc thường ngày.\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-the-thao-nam-promax-recycle-basics1-hong-marsala-1_10.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-the-thao-nam-promax-recycle-basics1-xanh-duong-1_54.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-the-thao-nam-promax-recycle-basics1-den-logo-moi-1_82.jpg" width=300>\n\nAnh thích kiểu nào hơn hay có cần xem thêm màu sắc nào không ạ?'}
            {'customer': 'mẫu khác nha', 'bot': 'Dạ, mình có thêm mấy mẫu áo thun nam này, anh xem thử nha:\n\n1.  **Áo Thun Nam Cotton Compact** (Mã: TSZ923)\n    Chất liệu 95% Cotton Compact, 5% Spandex co giãn 4 chiều, siêu mềm mịn, hạn chế xù lông và giữ form tốt. Form Regular Fit.\n    Giá: 229.000đ\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-thun-nam-cotton-compact-chong-nhan-den-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-thun-nam-cotton-compact-chong-nhan-xam-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-thun-nam-cotton-compact-chong-nhan-xanh-navy-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-thun-nam-cotton-compact-chong-nhan-trang-1.jpg" width=300>\n\n2.  **Áo Thun Dài Tay 100% Cotton Relax Fit** (Mã: LSZ711)\n    Chất liệu 100% Cotton mềm mại, thấm hút tốt, thoáng khí. Form Relax Fit rộng rãi, thoải mái.\n    Giá: 219.000đ\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-dai-tay-100-cotton-relax-fit-reu-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-dai-tay-100-cotton-relax-fit-trang-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/ao-dai-tay-100-cotton-relax-fit-den-1.jpg" width=300>\n\n3.  **Áo Thun Chạy Bộ Graphic Special** (Mã: TSZ878)\n    Chất liệu 92% Recycle Polyester, 8% Spandex co giãn 4 chiều, siêu nhẹ, thấm hút nhanh, khô nhanh. Form Regular Fit.\n    Giá: 159.000đ\n    <img src="https://n7media.coolmate.me/uploads/July2025/ao-thun-chay-bo-nam-graphic-special-den-2_50.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/July2025/ao-thun-chay-bo-nam-graphic-special-xanh-duong-4_21.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/July2025/ao-thun-chay-bo-nam-graphic-special-xanh-reu-2.jpg" width=300>\n\nAnh thấy mẫu nào ưng ý hay muốn xem thêm chi tiết gì không ạ?'}.
            Tin nhắn ngay trước đó: {'customer': 'cho mình xem quần kaki', 'bot': 'Ok anh bạn, về quần kaki thì mình có mấy mẫu này, anh xem qua nha:\n\n1.  **Quần Dài Nam Kaki Excool dáng Straight** (Mã: PAZ864)\n    Chất liệu 50% Polyester, 50% sợi Sorona, mềm mịn, thoáng mát, chống UV. Dáng Regular Straight thoải mái.\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-dang-straight-xam_(5).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-dang-straight-den_(3).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-dang-straight-xam-sang_(1).jpg" width=300>\n    Giá: 499.000đ\n\n2.  **Quần Dài Nam Kaki Excool** (Mã: PAZ896)\n    Chất liệu 50% Polyester, 50% Sợi Sorona, co giãn 4 chiều, siêu nhẹ, chống UV. Dáng Slimfit.\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-xam-den_(5).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/May2025/quan-dai-nam-kaki-excool-xam-nha_3.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-den_(5).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/November2025/quan-dai-nam-kaki-excool-1-1-xanh-navy_56.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-be-kaki_(2).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-xanh-dam_(8).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-xam-nhat_(5).jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/December2024/quan-dai-nam-kaki-excool-beige_(1).jpg" width=300>\n    Giá: 449.000đ\n\n3.  **Quần Dài Nam ECC Warp Pants dáng Slim** (Mã: PAZ863)\n    100% sợi Polyester PTT Microfiber, siêu mịn, nhẹ, thoáng khí, chống tia UV. Dáng Slim fit.\n    <img src="https://n7media.coolmate.me/uploads/September2025/quan-dai-nam-ecc-pants-dang-slim-fit-thoang-mat-den-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/quan-dai-nam-ecc-pants-dang-slim-fit-thoang-mat-navy-iris-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/quan-dai-nam-ecc-pants-dang-slim-fit-thoang-mat-xam-1.jpg" width=300>\n    <img src="https://n7media.coolmate.me/uploads/September2025/quan-dai-nam-ecc-pants-dang-slim-fit-thoang-mat-reu-kalamata-1.jpg" width=300>\n    Giá: 590.000đ\n\nAnh thích mẫu nào hay muốn xem thêm gì nữa không ạ?'}.
            Tin nhắn hiện tại: 'mẫu khác nha'.
            Hãy trả về đặc điểm của sản phẩm khách hàng đang tìm.
            Ví dụ:
                    Khách hàng: Tôi sắp đi đám cưới, cho tôi bộ quần áo phù hợp.
                    Trả về: Quần áo nam lịch sự, trang trọng để dự tiệc.

                    Khách hàng: Quần áo mặc cho mùa hè.
                    Trả về: Quần áo nam mặc hằng ngày, thấm hút nhanh khô, phù hợp cho các hoạt động ngoài trời.

                    Khách hàng: Áo đi làm.
                    Trả về: Áo nam lịch sự, thoải mái để mặc cả ngày, phù hợp để đi làm văn phòng."""

system_instruction='Chỉ trả về đoạn văn bản dùng để tìm kiếm hoặc câu hỏi thêm thông tin khách hàng, không gì khác!'
augmented_query=call_llm(prompt, system_instruction, temperature=1)
print(augmented_query)